baseURL = "https://willcocks.dev"
languageCode = "en-us"
title = "Dan"
theme = "m10c"
canonifyURLs = true
publishDir = "docs"

[params]
author = "Dan Willcocks"
description = "Engineer of all things Cloud, DevOps and Serverless Advocate"

  [[params.social]]
    name = "github"
    url = "https://github.com/dwillcocks"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/danielwillcocks/"

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  # lightColor = "#f5e3e0"
  # lightestColor = "#f5f5f5"
  primaryColor = "#1CE"
